language: python
python:
  - "2.7"

#Django & Database
env:
  -DJANGO=1.7 DB=mysql
  -DJANGO=1.7 DB=sqlite3
  # -MICROSITEDBNAME=test
  # -MICROSITEDBUSER=root
  # -MICROSITEDBPASS=root
  # -SGUSER=mp
  # -SGPWD=mp
# command to install dependencies
# before_install:
#   - mysql -e "create database IF NOT EXISTS test;" -uroot

install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - python manage.py test
  - coverage run --source=micro_admin,micro_blog,employee,microsite_front,pages,micro_kb manage.py test



after_success:
  coveralls
