language: python
python:
  - "2.7"

services:
  - mysql
  - elasticsearch
#Django & Database
addons:
  sudo: true
  postgresql: "9.3"

env:
  -DJANGO=1.7 DB=mysql
  -DJANGO=1.7 DB=sqlite3
  # -MICROSITEDBNAME= test
  # -MICROSITEDBUSER= root
  # -MICROSITEDBPASS= root
  # -SGUSER=mp
  # -SGPWD=mp
# command to install dependencies
# before_install:
#   - mysql -e "create database IF NOT EXISTS micro;" -u root -p "root"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install mysql-python --use-mirrors

#mysql db creation
before_script:
  - sleep 15
  - mysql -e 'create database test;' -u root
  - psql -c 'create database test;' -U postgres
# command to run tests
script:
  - python manage.py test
  - coverage run --source=micro_admin,micro_blog,employee,microsite_front,pages manage.py test

after_success:
  coveralls
