language: python
python:
  - "3.4"

services:
  - elasticsearch
  - redis-server
#Django & Database
addons:
  postgresql: "9.4"

sudo: false

env:
  -DJANGO=1.11 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - gem install sass
  - pip install npm
  - npm install less
  - pip install redis

#mysql db creation
before_script:
  - sleep 15
  - psql -c 'create database test;' -U postgres

# command to run tests
script:
  - python manage.py test
  - coverage run --source=micro_admin,micro_blog,microsite_front,pages manage.py test

after_success:
  coveralls
